const configs = {
  1: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: 0 },
    { xPos: 0.0, startAngle: 0 },
    { xPos: -1, startAngle: 0 },
    { xPos: -2, startAngle: 0 },
  ],
  2: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: Math.PI / 4, color: 1 },
    { xPos: 0.0, startAngle: 0 },
    { xPos: -1, startAngle: 0 },
    { xPos: -2, startAngle: 0 },
  ],
  3: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: Math.PI / 4, color: 1 },
    { xPos: 0.0, startAngle: Math.PI / 4, color: 1 },
    { xPos: -1, startAngle: 0 },
    { xPos: -2, startAngle: 0 },
  ],
  4: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: 0 },
    { xPos: 0.0, startAngle: 0 },
    { xPos: -1, startAngle: 0 },
    { xPos: -2, startAngle: -Math.PI / 4, color: 1 },
  ],
  5: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: Math.PI / 4, color: 1 },
    { xPos: 0.0, startAngle: 0 },
    { xPos: -1, startAngle: -Math.PI / 4, color: 1 },
    { xPos: -2, startAngle: -Math.PI / 4, color: 1 },
  ],
  6: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: Math.PI / 4, color: 1 },
    { xPos: 0.0, startAngle: Math.PI / 4, color: 1 },
    { xPos: -1, startAngle: -Math.PI / 4 },
    { xPos: -2, startAngle: -Math.PI / 4 },
  ],
  7: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: Math.PI / 4, color: 1 },
    { xPos: 0.0, startAngle: Math.PI / 4, color: 1 },
    { xPos: -1, startAngle: 0 },
    { xPos: -2, startAngle: -Math.PI / 4, color: 1 },
  ],
  8: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: Math.PI / 4, color: 1 },
    { xPos: 0.0, startAngle: 0 },
    { xPos: -1, startAngle: 0 },
    { xPos: -2, startAngle: -Math.PI / 4, color: 1 },
  ],
  9: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: 0 },
    // { xPos: 0.0, startAngle: 0 },
    { xPos: -1, startAngle: 0 },
    { xPos: -2, startAngle: -Math.PI / 4, color: 1 },
  ],
  10: [
    { xPos: 2, startAngle: Math.PI / 4, vel: -0.01, color: 1 },
    { xPos: 1, startAngle: 0 },
    { xPos: 0.0, startAngle: 0 },
    { xPos: -1, startAngle: 0 },
    { xPos: -2, startAngle: -Math.PI / 4, color: 1 },
  ],
  11: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: Math.PI / 6, vel: -0.01 },
    { xPos: 0.0, startAngle: 0 },
    { xPos: -1, startAngle: -Math.PI / 6, vel: 0.01 },
    { xPos: -2, startAngle: -Math.PI / 4, color: 1 },
  ],
  12: [
    { xPos: 2, startAngle: Math.PI / 4, color: 1 },
    { xPos: 1, startAngle: Math.PI / 6, vel: -0.01 },
    { xPos: 0.0, startAngle: 0 },
    { xPos: -1, startAngle: -Math.PI / 6, vel: 0.01 },
    { xPos: -2, startAngle: -Math.PI / 4, color: 1 },
  ],
};

export default configs;
